export const Projects = [
	{
		_id: '01',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/01',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '02',
		image: 'assets/project/project-grid-02.jpg',
		title: 'Big Life Lil Thug E ft (Desant, Fla, Ginjin ...)',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/02.jpg',
		url: '/projects/02',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '03',
		image: 'assets/project/project-grid-03.jpg',
		title: 'Халуун Маруужин Цомог B Production',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/03.jpg',
		url: '/projects/03',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '04',
		image: 'assets/project/project-grid-04.jpg',
		title: 'Vandebo',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/04.jpg',
		url: '/projects/04',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '05',
		image: 'assets/project/project-grid-05.jpg',
		title: 'ThunderZ Street Official Music Video',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/05.jpg',
		url: '/projects/05',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '06',
		image: 'assets/project/project-grid-06.jpg',
		title: 'Хар хун дэлхийн анхны OG цомгын...',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/06.jpg',
		url: '/projects/06',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '07',
		image: 'assets/project/project-grid-07.jpg',
		title: 'Маш Нууц 3: Дижитал 2022',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/07.jpg',
		url: '/projects/07',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '08',
		image: 'assets/project/project-grid-08.jpg',
		title: 'COVID-19 вакциныг улс орнуудад...',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/08.jpg',
		url: '/projects/08',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '09',
		image: 'assets/project/project-grid-09.jpg',
		title: 'Цагаан Үнс: Манга Номын Нээлт',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/09.jpg',
		url: '/projects/09',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '10',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/10.jpg',
		url: '/projects/10',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '11',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/11',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '12',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/12',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '13',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/13',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '14',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/14',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '15',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/15',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '16',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/16',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '17',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/17',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: '18',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/projects/18',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	}
]
