export const Projects = [
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-02.jpg',
		title: 'Big Life Lil Thug E ft (Desant, Fla, Ginjin ...)',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/02.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-03.jpg',
		title: 'Халуун Маруужин Цомог B Production',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/03.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-04.jpg',
		title: 'Vandebo',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/04.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-05.jpg',
		title: 'ThunderZ Street Official Music Video',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/05.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-06.jpg',
		title: 'Хар хун дэлхийн анхны OG цомгын...',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/06.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-07.jpg',
		title: 'Маш Нууц 3: Дижитал 2022',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/07.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-08.jpg',
		title: 'COVID-19 вакциныг улс орнуудад...',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/08.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-09.jpg',
		title: 'Цагаан Үнс: Манга Номын Нээлт',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/09.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/10.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	},
	{
		_id: 'id',
		image: 'assets/project/project-grid-01.jpg',
		title: 'Яаралтай Тусламжийн Тасгийнхан МУОАК',
		category: 'Кино',
		author: 'Nomadia Pictures',
		authorImg: 'assets/author-thumbs/01.jpg',
		url: '/project-details',
		date: '2022 оны 04 сарын 23',
		needed: 1875000,
		collected: 1500000
	}
]
